# Generated by Django 3.2.4 on 2021-07-18 06:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itap',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itap',
            name='users',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='itap',
            name='activation_key',
            field=models.CharField(default='WP6XC0', max_length=8),
        ),
        migrations.AlterField(
            model_name='itap',
            name='uuid',
            field=models.CharField(default=uuid.UUID('1e33b53d-57d7-4ba8-8e81-c237c560a36a'), max_length=36),
        ),
    ]
