# Generated by Django 3.2.4 on 2021-07-18 06:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210718_0638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itap',
            name='uuid',
        ),
        migrations.AddField(
            model_name='itap',
            name='seed',
            field=models.CharField(default=uuid.UUID('be0eac5f-6e4c-4933-83c7-9ea3a66216ff'), max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='itap',
            name='activation_key',
            field=models.CharField(default='CJ3H1JB2', max_length=8, unique=True),
        ),
    ]
