# Generated by Django 3.2.4 on 2021-07-18 06:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210718_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itap',
            name='activation_key',
            field=models.CharField(default='6BRS3M1F', max_length=8),
        ),
        migrations.AlterField(
            model_name='itap',
            name='seed',
            field=models.CharField(default=uuid.UUID('3917f1f0-df20-4f1f-8eb7-32e49f189764'), max_length=36),
        ),
    ]
