# Generated by Django 3.2.4 on 2021-07-18 06:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210718_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itap',
            name='activation_key',
            field=models.CharField(blank=True, default='25XL30cG', editable=False, max_length=8),
        ),
        migrations.AlterField(
            model_name='itap',
            name='seed',
            field=models.CharField(default=uuid.UUID('3bf64cf9-95ab-4c47-a142-83c42fd0b06d'), max_length=36),
        ),
    ]
