# Generated by Django 3.2.4 on 2021-07-18 06:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210718_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itap',
            name='activation_key',
            field=models.CharField(blank=True, default='b5DfanU3', editable=False, max_length=8),
        ),
        migrations.AlterField(
            model_name='itap',
            name='seed',
            field=models.CharField(default=uuid.UUID('8f48af9d-c75f-43c4-80f2-f2a306fd20df'), max_length=36),
        ),
    ]
