# Generated by Django 3.2.4 on 2021-07-18 07:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210718_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itap',
            name='seed',
            field=models.CharField(default=uuid.UUID('f732f9aa-9a09-42f4-8ece-87ad97daf179'), max_length=36),
        ),
    ]
