# Generated by Django 3.2.4 on 2021-07-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210718_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itap',
            name='activation_key',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='itap',
            name='seed',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
    ]
