# Generated by Django 3.2.4 on 2021-07-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210718_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itap',
            name='address',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='itap',
            name='name',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='itap',
            name='owner',
            field=models.EmailField(blank=True, default='', max_length=32),
        ),
    ]
