# Generated by Django 3.2.4 on 2021-07-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210718_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itap',
            name='address',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='itap',
            name='name',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='itap',
            name='owner',
            field=models.EmailField(default='', max_length=32),
        ),
    ]
