# Generated by Django 3.2.4 on 2021-07-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210718_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='itap',
            name='requested_slots',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itap',
            name='seed',
            field=models.CharField(blank=True, default='sad', max_length=36, null=True, unique=True),
        ),
    ]
