# Generated by Django 3.2.4 on 2021-07-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210718_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itap',
            name='requested_slots',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
