# Generated by Django 3.2.4 on 2021-07-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_itap_requested_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itap',
            name='requested_slots',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itap',
            name='seed',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
    ]
