# Generated by Django 3.2.4 on 2021-06-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArduinoKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=8)),
            ],
        ),
    ]
