# Generated by Django 3.2.4 on 2021-06-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_arduinokey'),
    ]

    operations = [
        migrations.CreateModel(
            name='iTap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=32)),
                ('activation_date', models.CharField(max_length=32)),
                ('iTap_key', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='iTapKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_key', models.CharField(default='null', max_length=8)),
                ('activated', models.BooleanField(default=False)),
                ('owner', models.CharField(default='null', max_length=32)),
            ],
        ),
        migrations.DeleteModel(
            name='ArduinoKey',
        ),
    ]
