# Generated by Django 3.2.4 on 2021-06-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210624_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='iTapActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='null', max_length=8)),
                ('activated', models.BooleanField(default=False)),
                ('owner', models.CharField(default='null', max_length=32)),
            ],
        ),
        migrations.DeleteModel(
            name='iTapKey',
        ),
        migrations.RemoveField(
            model_name='itap',
            name='iTap_key',
        ),
        migrations.AddField(
            model_name='itap',
            name='city',
            field=models.CharField(default='NULL', max_length=32),
        ),
        migrations.AddField(
            model_name='itap',
            name='key',
            field=models.CharField(default='null', max_length=8),
        ),
        migrations.AddField(
            model_name='itap',
            name='region',
            field=models.CharField(default='NULL', max_length=32),
        ),
        migrations.AddField(
            model_name='itap',
            name='slots',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='itap',
            name='tokens',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='itap',
            name='zipcode',
            field=models.CharField(default='NULL', max_length=32),
        ),
        migrations.AlterField(
            model_name='itap',
            name='activation_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='itap',
            name='address',
            field=models.CharField(default='NULL', max_length=32),
        ),
    ]
