# Generated by Django 3.2.4 on 2021-06-25 02:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210624_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_verification',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='itap',
            name='activation_date',
            field=models.DateField(verbose_name=datetime.datetime(2021, 6, 25, 2, 15, 32, 598229, tzinfo=utc)),
        ),
    ]
