# Generated by Django 3.2.4 on 2021-06-27 23:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210625_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itap',
            name='activation_date',
            field=models.DateField(verbose_name=datetime.datetime(2021, 6, 27, 23, 20, 25, 897258, tzinfo=utc)),
        ),
    ]
