# Generated by Django 3.2.4 on 2021-06-28 02:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 28, 2, 58, 49, 736551), max_length=255, verbose_name='Datetime creation'),
        ),
        migrations.AddField(
            model_name='itap',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 28, 2, 58, 49, 738972)),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 28, 2, 58, 49, 737162)),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='email',
            field=models.EmailField(default='-', max_length=32),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='token',
            field=models.CharField(default='-', max_length=255),
        ),
    ]
