# Generated by Django 3.2.4 on 2021-06-28 02:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210628_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 28, 2, 59, 59, 184416), max_length=255, verbose_name='Datetime creation'),
        ),
        migrations.AlterField(
            model_name='itap',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 28, 2, 59, 59, 186655)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 28, 2, 59, 59, 184894)),
        ),
    ]
